/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module;

import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.core.util.MultivaluedMapImpl;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.oauth.*;

import javax.ws.rs.core.MultivaluedMap;


/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Module(name="vimeo", schemaVersion="1.0-SNAPSHOT")
@OAuth(requestTokenUrl = "https://vimeo.com/oauth/request_token",
        accessTokenUrl = "https://vimeo.com/oauth/access_token",
        authorizationUrl = "https://vimeo.com/oauth/authorize")
public class vimeoConnector
{
    /**
     * Configurable
     */
    @Configurable
    @OAuthConsumerKey
    private String vimeoOAuthClientID;
    @Configurable
    @OAuthConsumerSecret
    private String vimeoOAuthClientSecret;

    /**
     * Jersey client
     */
    private Client client;
    private WebResource webResource;
    private MultivaluedMap<String, String> queryParams;
    private String jsonResponse;
    private String serviceMethod;
    private static final String BASE_URI ="http://vimeo.com/api/rest/v2";


    /**
     * Constructor
     */
    public vimeoConnector()
    {
        client = new Client();
    }

    /**
     * Get property
     *  
     */
    public String getVimeoOAuthClientID(){
        return this.vimeoOAuthClientID;
    }

    /**
     * Set property
     *
     * @param vimeoOAuthClientID - Client ID (Also know as Consumer Key or API Key)
     */
    public void setVimeoOAuthClientID(String vimeoOAuthClientID)
    {
        this.vimeoOAuthClientID = vimeoOAuthClientID;
    }

    /**
     * Get property
     */
    public String getVimeoOAuthClientSecret(){
        return this.vimeoOAuthClientSecret;
    }
    
    /**
     * Set property
     *
     * @param vimeoOAuthClientSecret - Client Secret (Also known as Consumer Secret or API Secret)
     */
    public void setVimeoOAuthClientSecret(String vimeoOAuthClientSecret)
    {
        this.vimeoOAuthClientSecret = vimeoOAuthClientSecret;
    }

    /**
     * Vimeo Echo Test processor
     *
     * {@sample.xml ../../../doc/vimeo-connector.xml.sample vimeo:echo-test}
     *
     * @param vimeoOAuthClientID OAuth API Key
     * @param vimeoOAuthClientSecret API Secret
     * @param echoString test parameter will be simply echoed back
     * @return echos back input parameter string
     */
    @Processor
    public String echoTest(@OAuthAccessToken String vimeoOAuthClientID,
                                @OAuthAccessTokenSecret String vimeoOAuthClientSecret,
                                String echoString)
    {
        /*
         * MESSAGE PROCESSOR CODE GOES HERE
         */
        // Set service method
        serviceMethod = "vimeo.test.echo";

        webResource = client.resource(BASE_URI);
        queryParams = new MultivaluedMapImpl();

        // Set request fields
        queryParams.add("method", serviceMethod);
        queryParams.add("echoString", echoString);

        // Invoke service
        jsonResponse = webResource.queryParams(queryParams).get(String.class);

        return jsonResponse;
    }
}
