/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module;

import org.apache.commons.httpclient.HttpClient;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.oauth.*;
import org.mule.api.annotations.rest.*;

import java.io.IOException;


/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */

@OAuth(requestTokenUrl = vimeoConnector.REQUEST_TOKEN_URL,
        accessTokenUrl = vimeoConnector.ACCESS_TOKEN_URL,
        authorizationUrl = vimeoConnector.AUTHORIZATION_URL)
@Connector(name="vimeo", schemaVersion="1.0-SNAPSHOT")
public abstract class vimeoConnector
{

    public static final String REQUEST_TOKEN_URL = "https://vimeo.com/oauth/request_token";
    public static final String AUTHORIZATION_URL = "https://vimeo.com/oauth/access_token";
    public static final String ACCESS_TOKEN_URL = "https://vimeo.com/oauth/access_token";
    public static final String BASE_URI = "http://vimeo.com/api/rest/v2?method=";


    @RestHttpClient
    private HttpClient httpClient;

    /**
     * Configurable parameters
     */

    /*
     * vimeoOAuthClientID - Client ID (Also known as Consumer Key or API Key)
     */
    @Configurable
    @OAuthConsumerKey
    private String vimeoOAuthClientID;

    /**
     * vimeoOAuthClientSecret - Client Secret (Also known as Consumer Secret or API Secret)
     */
    @Configurable
    @OAuthConsumerSecret
    private String vimeoOAuthClientSecret;

    /**
     * responseFormat - options for response format include json, jsonp, php or xml (default)
     */
    @OAuthAccessToken
    private String accessToken;

    @OAuthAccessTokenSecret
    private String accessTokenSecret;

    public vimeoConnector()
    {
        httpClient = new HttpClient();
    }

    @Processor
    @OAuthProtected
    @RestCall(uri = BASE_URI+"vimeo.test.echo", method = HttpMethod.GET)
    public abstract String getTestEcho(@RestQueryParam("echoString") String echoString,
                                       @RestQueryParam("format") String format) throws IOException;

    /**
     * Accessor methods
     */

    public HttpClient getHttpClient(){
        return this.httpClient;
    }

    /**
     * Set property
     *
     * @param httpClient
     */

    public void setHttpClient(HttpClient httpClient){
        this.httpClient = httpClient;
    }

    public String getVimeoOAuthClientID(){
        return this.vimeoOAuthClientID;
    }

    /**
     * Set property
     *
     * @param vimeoOAuthClientID - Client ID (Also know as Consumer Key or API Key)
     */

    public void setVimeoOAuthClientID(String vimeoOAuthClientID)
    {
        this.vimeoOAuthClientID = vimeoOAuthClientID;
    }

    public String getVimeoOAuthClientSecret(){
        return this.vimeoOAuthClientSecret;
    }

    /**
     * Set property
     *
     * @param vimeoOAuthClientSecret - Client Secret (Also know as Consumer Secret or API Secret)
     */

    public void setVimeoOAuthClientSecret(String vimeoOAuthClientSecret)
    {
        this.vimeoOAuthClientSecret = vimeoOAuthClientSecret;
    }

    public String getAccessToken() {
        return accessToken;
    }

    /**
     * Set property
     *
     * @param accessToken
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * Set property
     *
     * @param accessTokenSecret
     */
    public void setAccessTokenSecret(String accessTokenSecret) {
        this.accessTokenSecret = accessTokenSecret;
    }

    public String getAccessTokenSecret() {
        return accessTokenSecret;
    }
}
