/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module;

import org.junit.Before;
import org.junit.Test;
import org.mule.api.MuleEvent;
import org.mule.api.lifecycle.InitialisationException;
import org.mule.construct.Flow;
import org.mule.tck.junit4.AbstractMuleContextTestCase;
import org.mule.tck.junit4.FunctionalTestCase;

import static org.junit.Assert.assertEquals;

public class vimeoConnectorTest extends FunctionalTestCase
{
    private String apiAccessKey;
    private String apiAccessKeySecret;
    private String oAuthClientID;
    private String oAuthClientSecret;

    @Override
    protected String getConfigResources()
    {
        return "mule-config.xml";
    }

    @Before
    public void setUp() throws InitialisationException
    {
        //apiAccessKeys - Used for testing to access Your Vimeo account
        apiAccessKey = System.getenv("user.key.vimeo.access");
        apiAccessKeySecret = System.getenv("user.key.vimeo.secret");

        //OAuth Client Id & Secret - Used for testing to initiate OAuth authorization.
        oAuthClientID = System.getenv("user.key.vimeo.oauth.clientId");
        oAuthClientSecret = System.getenv("user.key.vimeo.oauth.clientSecret");

        //TODO: Inovke vimeo:authorize processor to initialize OAuth access key.
    }

    @Test
    public void testEchoFlow() throws Exception
    {
        runFlowAndExpect("echoTestFlow", "ping");
    }

    /**
    * Run the flow specified by name and assert equality on the expected output
    *
    * @param flowName The name of the flow to run
    * @param expect The expected output
    */
    protected <T> void runFlowAndExpect(String flowName, T expect) throws Exception
    {
        Flow flow = lookupFlowConstruct(flowName);
        MuleEvent event = AbstractMuleContextTestCase.getTestEvent(null);
        MuleEvent responseEvent = flow.process(event);

        assertEquals(expect, responseEvent.getMessage().getPayload());
    }

    /**
    * Run the flow specified by name using the specified payload and assert
    * equality on the expected output
    *
    * @param flowName The name of the flow to run
    * @param expect The expected output
    * @param payload The payload of the input event
    */
    protected <T, U> void runFlowWithPayloadAndExpect(String flowName, T expect, U payload) throws Exception
    {
        Flow flow = lookupFlowConstruct(flowName);
        MuleEvent event = AbstractMuleContextTestCase.getTestEvent(payload);
        MuleEvent responseEvent = flow.process(event);

        assertEquals(expect, responseEvent.getMessage().getPayload());
    }

    /**
     * Retrieve a flow by name from the registry
     *
     * @param name Name of the flow to retrieve
     */
    protected Flow lookupFlowConstruct(String name)
    {
        return (Flow) AbstractMuleContextTestCase.muleContext.getRegistry().lookupFlowConstruct(name);
    }
}
